"""empty message

Revision ID: 1ce6f07fd041
Revises: 41761be5b2ea
Create Date: 2023-04-09 05:03:49.464292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ce6f07fd041'
down_revision = '41761be5b2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.drop_constraint('forum_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('forum_ibfk_2', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
