"""empty message

Revision ID: 38a5cae9c325
Revises: dc214f762c22
Create Date: 2023-01-03 03:37:55.987338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38a5cae9c325'
down_revision = 'dc214f762c22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jkyw', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tag', sa.String(length=10), nullable=False))
        batch_op.create_unique_constraint(None, ['tag'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jkyw', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tag')

    # ### end Alembic commands ###
