"""empty message

Revision ID: 49e020787be1
Revises: d6a1d7ded7b5
Create Date: 2023-04-09 11:30:43.965744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '49e020787be1'
down_revision = 'd6a1d7ded7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('join_time',
               existing_type=mysql.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('forum', schema=None) as batch_op:
        batch_op.alter_column('join_time',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
