"""empty message

Revision ID: cc6993997e57
Revises: 7fe3cd96c82d
Create Date: 2023-04-09 10:52:17.112050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cc6993997e57'
down_revision = '7fe3cd96c82d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.drop_column('join_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_captcha', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_time', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
