"""empty message

Revision ID: cf7410bb9c23
Revises: 49e020787be1
Create Date: 2023-04-09 13:35:05.036468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf7410bb9c23'
down_revision = '49e020787be1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('email_id', sa.String(length=100), nullable=False),
    sa.Column('join_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['email_id'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum')
    # ### end Alembic commands ###
