"""empty message

Revision ID: dc214f762c22
Revises: c82f7a857b87
Create Date: 2023-01-03 03:12:10.549211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc214f762c22'
down_revision = 'c82f7a857b87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jkyw',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('jkyw_page', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jkyw')
    # ### end Alembic commands ###
